title: GuGg - GH Han
description: 한국현(GH Han)(GuGg 국끄) 개인 블로그 Blog for personal and making "Updateam"

url: http://gugghan.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: gugghan
   twitter: gugghan
   facebook: gugghan
   email: gugghan@gmail.com

google_analytics: "UA-63291251-1"
